import {
  Map as MapIcon,
  Monitor,
  Smartphone,
  BarChart3,
  Database,
  Megaphone,
  RefreshCw,
  type LucideIcon,
} from "lucide-react";

export type ContentItem = {
  text: string;
  /** Path under /systemic/<slug>/, e.g. "contains-1.png". Falls back to an icon tile if missing or fails to load. */
  image?: string;
};

export type SystemTileDef = {
  slug: string;
  icon: LucideIcon;
  title: string;
  layer?: string;
  desc: string;
  contains: ContentItem[];
  outcomes: ContentItem[];
};

export const SYSTEM_TILES: SystemTileDef[] = [
  {
    slug: "dg-app",
    icon: Smartphone,
    title: "DG App",
    layer: "The Core Retail Enablement Layer",
    desc: "For Demand Generators to discover the market potential in their area and systematically engage with local customer groups.",
    contains: [
      {
        text: "Market Potential Mapping — list of top clusters in the area (their potential, competitive strength, ease of sales)",
        image: "contains-1.png",
      },
      {
        text: "Cluster Engagement Plan — customer groups, value proposition, contribution event recommendations",
        image: "contains-2.png",
      },
      {
        text: "Customer Sales Enablement — pamphlets, decks and customised action points at every sale stage, from identification and contacting to proposing solutions, closing and follow-up",
        image: "contains-3.png",
      },
      { text: "Cluster potential report", image: "contains-4.png" },
      { text: "Cluster engagement report", image: "contains-5.png" },
    ],
    outcomes: [
      { text: "Access level of the DG in a cluster", image: "outcomes-1.png" },
      { text: "Overall market potential in a cluster", image: "outcomes-2.png" },
      {
        text: "Action plans for cluster engagement — camps, events, and captured contacts of contractors, retailers and stakeholders",
        image: "outcomes-3.png",
      },
      { text: "Enablers used for a prospect sale" },
      { text: "Sales engagement happenings" },
    ],
  },
  {
    slug: "asm-dashboard",
    icon: BarChart3,
    title: "ASM Dashboard",
    layer: "Tactical Decision Layer",
    desc: "Help ASMs identify where DGs are concentrating their efforts, assess cluster-level priorities, and measure the progress and effectiveness of co-created cluster engagement plans.",
    contains: [
      { text: "Top market clusters (potential & access) in the area" },
      { text: "What DGs are prioritizing as clusters" },
      { text: "Penetration level progress at each cluster" },
      { text: "Consolidated & individual cluster reports generated by DGs" },
      { text: "Consolidated & individual cluster engagement plans co-created" },
      { text: "Effectiveness of engagement plans co-created" },
    ],
    outcomes: [
      { text: "High potential – high access clusters in the area" },
      { text: "% of DGs prioritizing each cluster" },
      { text: "% of DGs prioritizing each cluster type (e.g. HP–HA, HP–LA)" },
      { text: "DG-wise execution strategy status" },
      { text: "Where DGs stand in the sales funnel" },
      { text: "Penetration % and MoM % increase at each cluster" },
      { text: "% conversion from cluster engagement" },
    ],
  },
  {
    slug: "leadership-dashboard",
    icon: Monitor,
    title: "Leadership Dashboard",
    layer: "Strategic Intelligence Layer",
    desc: "To give the leadership a view into top market clusters and enable them to strategize market penetration with the help of the sales teams.",
    contains: [
      { text: "Top market clusters (potential & access)" },
      { text: "What ASMs & DGs are prioritizing as clusters" },
      { text: "Penetration level progress at each cluster" },
    ],
    outcomes: [
      { text: "High potential – high access clusters across the country, states or regions" },
      { text: "% of DGs prioritizing each cluster" },
      { text: "% of DGs prioritizing each cluster type (e.g. HP–HA, HP–LA)" },
      { text: "DG-wise execution strategy status" },
      { text: "Where DGs stand in the sales funnel" },
      { text: "Penetration % and MoM % increase at each cluster" },
    ],
  },
  {
    slug: "knowledge-base",
    icon: Database,
    title: "Market & Cluster Knowledge Base",
    layer: "AI + Rules Engine + Knowledge Base Layer",
    desc: "The core analytics component in the backend which generates, stores & captures dynamic knowledge intelligence for the market & clusters.",
    contains: [
      { text: "All major clusters in a region" },
      { text: "Cluster revenue potential, competitive strength, ease of sale, and their sources" },
      { text: "Cluster-wise customer groups, value proposition pitch, and contribution events" },
      { text: "Cluster-wise sales enablers — pamphlets, decks, customised action points — and prospects at each sales stage" },
    ],
    outcomes: [
      { text: "Cluster access level & overall cluster potential" },
      { text: "Contacts — contractors, retailers, other stakeholders — specific to each cluster" },
      { text: "DG-targeted customer groups, value proposition and contribution events planned for cluster engagement" },
      { text: "DGs' chosen sales enablers, captured" },
      { text: "Effectiveness of the engagement plan & contribution events" },
    ],
  },
  {
    slug: "nudges-campaigns",
    icon: Megaphone,
    title: "Nudges / Campaigns",
    layer: "Execution Layer",
    desc: "To use the knowledge base layer to provide actionable recommendations to conduct contribution events & execute sales effectively for DGs, and enable ASMs to nudge the DGs.",
    contains: [
      {
        text: "Nudge engine — how to effectively execute the engagement plans devised by DGs, with triggers to move through the sales cycle along the way",
      },
      { text: "ASM nudges — area-level recommendations on which clusters to target for the week, for their DGs" },
    ],
    outcomes: [
      { text: "Best practices nudge — best execution practices for contribution events" },
      { text: "Potential clusters nudge — signals to go after HP–HA clusters on priority basis" },
      { text: "Sales nudge — nudges at each stage of a prospect's sales cycle to execute it effectively" },
    ],
  },
  {
    slug: "continuous-evolution",
    icon: RefreshCw,
    title: "Continuous Evolution",
    layer: "Ongoing Improvement Layer",
    desc: "To ensure the Market Discovery System itself evolves based on field reality — continuously refining the cluster engagement plan, triggers for contribution events, pamphlets, decks provided, and sales enablers based on their effectiveness in the engagement.",
    contains: [
      { text: "Engagement & enablers performance review engine" },
      { text: "How pamphlets, decks, etc. are being used" },
      { text: "Gaps in the cluster engagement plan" },
      { text: "How sales enablers are aiding in moving prospects" },
    ],
    outcomes: [
      { text: "Design effectiveness measures" },
      { text: "Overall cluster potential vs. ease of cluster engagement & sales" },
      { text: "Customer cluster engagement plan effectiveness" },
      { text: "Sales enablers effectiveness" },
    ],
  },
];

export function getSystemTile(slug: string): SystemTileDef | undefined {
  return SYSTEM_TILES.find((t) => t.slug === slug);
}

// Kept for the meta home's Product View tile icon typing.
export const MetaMapIcon = MapIcon;
