import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import {
  Map as MapIcon,
  Monitor,
  LayoutDashboard,
  ArrowRight,
  Smartphone,
  BarChart3,
  Database,
  Megaphone,
  RefreshCw,
  Package,
  Gauge,
  CheckCircle2,
  Target,
} from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Paints — Market Intelligence System" },
      {
        name: "description",
        content: "Select your interface to continue.",
      },
    ],
  }),
  component: MetaHome,
});

type ViewMode = "systemic" | "product";

type ProductTileDef = {
  icon: typeof MapIcon;
  title: string;
  desc: string;
  to: "/market-discovery" | "/leadership" | "/dashboard";
  cta: string;
};

const PRODUCT_TILES: ProductTileDef[] = [
  {
    icon: MapIcon,
    title: "Market Discovery System",
    desc: "Map your market clusters by revenue potential, access and competitive strength, build cluster engagement plans, and move prospects through the sales funnel.",
    to: "/market-discovery",
    cta: "Open Market Discovery",
  },
  {
    icon: Monitor,
    title: "Leadership Analytics App",
    desc: "Aggregated visibility for leadership across all DGs — cluster prioritisation, market penetration, engagement focus and execution tracking.",
    to: "/leadership",
    cta: "Open Leadership App",
  },
  {
    icon: LayoutDashboard,
    title: "DG Dashboard",
    desc: "Your personal performance snapshot — KPIs, conversion trends and cluster-wise progress for your own market.",
    to: "/dashboard",
    cta: "Open My Dashboard",
  },
];

type SystemTileDef = {
  icon: typeof MapIcon;
  title: string;
  layer?: string;
  desc: string;
  contains: string[];
  outcomes: string[];
  // Reserved for imagery to be added later, keyed by tile so it's a drop-in.
  image?: string;
};

const SYSTEM_TILES: SystemTileDef[] = [
  {
    icon: Smartphone,
    title: "DG App",
    layer: "The Core Retail Enablement Layer",
    desc: "For Demand Generators to discover the market potential in their area and systematically engage with local customer groups.",
    contains: [
      "Market Potential Mapping — top clusters in the area, their potential, competitive strength and ease of sales",
      "Cluster Engagement Plan — customer groups, value proposition, contribution event recommendations",
      "Customer Sales Enablement — pamphlets, decks and customised action points at every sale stage, from identification and contacting to proposing solutions, closing and follow-up",
      "Cluster potential report",
      "Cluster engagement report",
    ],
    outcomes: [
      "Access level of the DG in a cluster",
      "Overall market potential in a cluster",
      "Action plans for cluster engagement — camps, events, and captured contacts of contractors, retailers and stakeholders",
      "Enablers used for a prospect sale",
      "Sales engagement happenings",
    ],
  },
  {
    icon: BarChart3,
    title: "ASM Dashboard",
    layer: "Tactical Decision Layer",
    desc: "Help ASMs identify where DGs are concentrating their efforts, assess cluster-level priorities, and measure the progress and effectiveness of co-created cluster engagement plans.",
    contains: [
      "Top market clusters (potential & access) in the area",
      "What DGs are prioritizing as clusters",
      "Penetration level progress at each cluster",
      "Consolidated & individual cluster reports generated by DGs",
      "Consolidated & individual cluster engagement plans co-created",
      "Effectiveness of engagement plans co-created",
    ],
    outcomes: [
      "High potential – high access clusters in the area",
      "% of DGs prioritizing each cluster",
      "% of DGs prioritizing each cluster type (e.g. HP–HA, HP–LA)",
      "DG-wise execution strategy status",
      "Where DGs stand in the sales funnel",
      "Penetration % and MoM % increase at each cluster",
      "% conversion from cluster engagement",
    ],
  },
  {
    icon: Monitor,
    title: "Leadership Dashboard",
    layer: "Strategic Intelligence Layer",
    desc: "To give the leadership a view into top market clusters and enable them to strategize market penetration with the help of the sales teams.",
    contains: [
      "Top market clusters (potential & access)",
      "What ASMs & DGs are prioritizing as clusters",
      "Penetration level progress at each cluster",
    ],
    outcomes: [
      "High potential – high access clusters across the country, states or regions",
      "% of DGs prioritizing each cluster",
      "% of DGs prioritizing each cluster type (e.g. HP–HA, HP–LA)",
      "DG-wise execution strategy status",
      "Where DGs stand in the sales funnel",
      "Penetration % and MoM % increase at each cluster",
    ],
  },
  {
    icon: Database,
    title: "Market & Cluster Knowledge Base",
    layer: "AI + Rules Engine + Knowledge Base Layer",
    desc: "The core analytics component in the backend which generates, stores & captures dynamic knowledge intelligence for the market & clusters.",
    contains: [
      "All major clusters in a region",
      "Cluster revenue potential, competitive strength, ease of sale, and their sources",
      "Cluster-wise customer groups, value proposition pitch, and contribution events",
      "Cluster-wise sales enablers — pamphlets, decks, customised action points — and prospects at each sales stage",
    ],
    outcomes: [
      "Cluster access level & overall cluster potential",
      "Contacts — contractors, retailers, other stakeholders — specific to each cluster",
      "DG-targeted customer groups, value proposition and contribution events planned for cluster engagement",
      "DGs' chosen sales enablers, captured",
      "Effectiveness of the engagement plan & contribution events",
    ],
  },
  {
    icon: Megaphone,
    title: "Nudges / Campaigns",
    layer: "Execution Layer",
    desc: "To use the knowledge base layer to provide actionable recommendations to conduct contribution events & execute sales effectively for DGs, and enable ASMs to nudge the DGs.",
    contains: [
      "Nudge engine — how to effectively execute the engagement plans devised by DGs, with triggers to move through the sales cycle along the way",
      "ASM nudges — area-level recommendations on which clusters to target for the week, for their DGs",
    ],
    outcomes: [
      "Best practices nudge — best execution practices for contribution events",
      "Potential clusters nudge — signals to go after HP–HA clusters on priority basis",
      "Sales nudge — nudges at each stage of a prospect's sales cycle to execute it effectively",
    ],
  },
  {
    icon: RefreshCw,
    title: "Continuous Evolution",
    layer: "Ongoing Improvement Layer",
    desc: "To ensure the Market Discovery System itself evolves based on field reality — continuously refining the cluster engagement plan, triggers for contribution events, pamphlets, decks provided, and sales enablers based on their effectiveness in the engagement.",
    contains: [
      "Engagement & enablers performance review engine",
      "How pamphlets, decks, etc. are being used",
      "Gaps in the cluster engagement plan",
      "How sales enablers are aiding in moving prospects",
    ],
    outcomes: [
      "Design effectiveness measures",
      "Overall cluster potential vs. ease of cluster engagement & sales",
      "Customer cluster engagement plan effectiveness",
      "Sales enablers effectiveness",
    ],
  },
];

function MetaHome() {
  const [view, setView] = useState<ViewMode>("systemic");
  const [openTile, setOpenTile] = useState<SystemTileDef | null>(null);

  return (
    <div className="flex min-h-[100dvh] items-center justify-center bg-background p-6">
      <div className={cn("w-full space-y-8", view === "systemic" ? "max-w-6xl" : "max-w-4xl")}>
        <div className="space-y-3 text-center">
          <p className="text-lg font-medium tracking-wide text-muted-foreground">Paints</p>
          <h1 className="font-display text-4xl font-bold leading-tight text-foreground">
            Market Intelligence System
          </h1>
          <p className="text-sm text-muted-foreground">
            {view === "systemic" ? "How the system works, end to end" : "Select your interface to continue"}
          </p>

          <div className="inline-flex items-center rounded-full border border-border bg-card p-1 text-sm shadow-sm">
            <button
              type="button"
              onClick={() => setView("systemic")}
              className={cn(
                "rounded-full px-4 py-1.5 font-medium transition-colors",
                view === "systemic" ? "bg-navy text-navy-foreground" : "text-muted-foreground hover:text-foreground",
              )}
            >
              Systemic View
            </button>
            <button
              type="button"
              onClick={() => setView("product")}
              className={cn(
                "rounded-full px-4 py-1.5 font-medium transition-colors",
                view === "product" ? "bg-navy text-navy-foreground" : "text-muted-foreground hover:text-foreground",
              )}
            >
              Product View
            </button>
          </div>
        </div>

        {view === "product" ? (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            {PRODUCT_TILES.map(({ icon: Icon, title, desc, to, cta }) => (
              <Link
                key={to}
                to={to}
                className="group flex flex-col rounded-2xl border border-border bg-card p-6 text-left shadow-sm transition-shadow hover:shadow-lg"
              >
                <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-critical/10 text-critical transition-colors group-hover:bg-critical group-hover:text-white">
                  <Icon className="h-7 w-7" />
                </div>
                <h2 className="font-display text-xl font-bold leading-tight text-foreground">{title}</h2>
                <p className="mb-4 mt-1 flex-1 text-sm text-muted-foreground">{desc}</p>
                <span className="inline-flex items-center justify-center gap-1.5 rounded-md border border-border bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors group-hover:border-critical group-hover:text-critical">
                  {cta} <ArrowRight className="h-4 w-4" />
                </span>
              </Link>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {SYSTEM_TILES.map((tile) => {
              const Icon = tile.icon;
              return (
                <button
                  key={tile.title}
                  type="button"
                  onClick={() => setOpenTile(tile)}
                  className="group flex flex-col rounded-2xl border border-border bg-card p-6 text-left shadow-sm transition-shadow hover:shadow-lg"
                >
                  <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-navy/10 text-navy transition-colors group-hover:bg-navy group-hover:text-white">
                    <Icon className="h-7 w-7" />
                  </div>
                  <h2 className="font-display text-lg font-bold leading-tight text-foreground">{tile.title}</h2>
                  {tile.layer && (
                    <span className="mt-1 inline-block w-fit rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                      {tile.layer}
                    </span>
                  )}
                  <p className="mt-3 flex-1 text-sm text-muted-foreground">{tile.desc}</p>
                  <span className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-navy transition-colors group-hover:text-critical">
                    View details <ArrowRight className="h-4 w-4" />
                  </span>
                </button>
              );
            })}
          </div>
        )}
      </div>

      <Dialog open={openTile !== null} onOpenChange={(o) => !o && setOpenTile(null)}>
        <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
          {openTile && (
            <>
              <DialogHeader>
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-navy/10 text-navy">
                    <openTile.icon className="h-6 w-6" />
                  </div>
                  <div className="min-w-0">
                    <DialogTitle className="font-display text-xl">{openTile.title}</DialogTitle>
                    {openTile.layer && (
                      <span className="mt-0.5 inline-block w-fit rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                        {openTile.layer}
                      </span>
                    )}
                  </div>
                </div>
              </DialogHeader>

              <p className="text-sm text-muted-foreground">{openTile.desc}</p>

              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div className="rounded-xl border border-border bg-muted/30 p-4">
                  <div className="mb-2 flex items-center gap-2">
                    <Package className="h-4 w-4 text-navy" />
                    <h3 className="font-display text-sm font-bold text-foreground">What it contains</h3>
                  </div>
                  <ul className="space-y-2">
                    {openTile.contains.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                        <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-navy" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-xl border border-border bg-muted/30 p-4">
                  <div className="mb-2 flex items-center gap-2">
                    <Gauge className="h-4 w-4 text-critical" />
                    <h3 className="font-display text-sm font-bold text-foreground">Measures / Outcomes</h3>
                  </div>
                  <ul className="space-y-2">
                    {openTile.outcomes.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                        <Target className="mt-0.5 h-3.5 w-3.5 shrink-0 text-critical" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
