/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as ConnectsIndexRouteImport } from './routes/connects/index'
import { Route as MapClusterIdRouteImport } from './routes/map/$clusterId'
import { Route as ConnectsClusterIdRouteImport } from './routes/connects/$clusterId'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectsIndexRoute = ConnectsIndexRouteImport.update({
  id: '/connects/',
  path: '/connects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapClusterIdRoute = MapClusterIdRouteImport.update({
  id: '/map/$clusterId',
  path: '/map/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectsClusterIdRoute = ConnectsClusterIdRouteImport.update({
  id: '/connects/$clusterId',
  path: '/connects/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/connects/$clusterId': typeof ConnectsClusterIdRoute
  '/map/$clusterId': typeof MapClusterIdRoute
  '/connects/': typeof ConnectsIndexRoute
  '/map/': typeof MapIndexRoute
  '/plan/': typeof PlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/connects/$clusterId': typeof ConnectsClusterIdRoute
  '/map/$clusterId': typeof MapClusterIdRoute
  '/connects': typeof ConnectsIndexRoute
  '/map': typeof MapIndexRoute
  '/plan': typeof PlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/connects/$clusterId': typeof ConnectsClusterIdRoute
  '/map/$clusterId': typeof MapClusterIdRoute
  '/connects/': typeof ConnectsIndexRoute
  '/map/': typeof MapIndexRoute
  '/plan/': typeof PlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/connects/$clusterId'
    | '/map/$clusterId'
    | '/connects/'
    | '/map/'
    | '/plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/connects/$clusterId'
    | '/map/$clusterId'
    | '/connects'
    | '/map'
    | '/plan'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/connects/$clusterId'
    | '/map/$clusterId'
    | '/connects/'
    | '/map/'
    | '/plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  ConnectsClusterIdRoute: typeof ConnectsClusterIdRoute
  MapClusterIdRoute: typeof MapClusterIdRoute
  ConnectsIndexRoute: typeof ConnectsIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connects/': {
      id: '/connects/'
      path: '/connects'
      fullPath: '/connects/'
      preLoaderRoute: typeof ConnectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$clusterId': {
      id: '/map/$clusterId'
      path: '/map/$clusterId'
      fullPath: '/map/$clusterId'
      preLoaderRoute: typeof MapClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connects/$clusterId': {
      id: '/connects/$clusterId'
      path: '/connects/$clusterId'
      fullPath: '/connects/$clusterId'
      preLoaderRoute: typeof ConnectsClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  ConnectsClusterIdRoute: ConnectsClusterIdRoute,
  MapClusterIdRoute: MapClusterIdRoute,
  ConnectsIndexRoute: ConnectsIndexRoute,
  MapIndexRoute: MapIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
