/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesEnablementRouteImport } from './routes/sales-enablement'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MarketPotentialRouteImport } from './routes/market-potential'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesEnablementIndexRouteImport } from './routes/sales-enablement.index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as PlanPastRoadmapRouteImport } from './routes/plan/past-roadmap'
import { Route as MapClusterIdRouteImport } from './routes/map/$clusterId'
import { Route as SalesEnablementClusterIdIndexRouteImport } from './routes/sales-enablement.$clusterId.index'
import { Route as PlanClusterIdIndexRouteImport } from './routes/plan/$clusterId.index'
import { Route as SalesEnablementClusterIdProspectIdRouteImport } from './routes/sales-enablement.$clusterId.$prospectId'
import { Route as PlanClusterIdReviewRouteImport } from './routes/plan/$clusterId.review'

const SalesEnablementRoute = SalesEnablementRouteImport.update({
  id: '/sales-enablement',
  path: '/sales-enablement',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPotentialRoute = MarketPotentialRouteImport.update({
  id: '/market-potential',
  path: '/market-potential',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEnablementIndexRoute = SalesEnablementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesEnablementRoute,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPastRoadmapRoute = PlanPastRoadmapRouteImport.update({
  id: '/plan/past-roadmap',
  path: '/plan/past-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MapClusterIdRoute = MapClusterIdRouteImport.update({
  id: '/map/$clusterId',
  path: '/map/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEnablementClusterIdIndexRoute =
  SalesEnablementClusterIdIndexRouteImport.update({
    id: '/$clusterId/',
    path: '/$clusterId/',
    getParentRoute: () => SalesEnablementRoute,
  } as any)
const PlanClusterIdIndexRoute = PlanClusterIdIndexRouteImport.update({
  id: '/plan/$clusterId/',
  path: '/plan/$clusterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEnablementClusterIdProspectIdRoute =
  SalesEnablementClusterIdProspectIdRouteImport.update({
    id: '/$clusterId/$prospectId',
    path: '/$clusterId/$prospectId',
    getParentRoute: () => SalesEnablementRoute,
  } as any)
const PlanClusterIdReviewRoute = PlanClusterIdReviewRouteImport.update({
  id: '/plan/$clusterId/review',
  path: '/plan/$clusterId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/market-potential': typeof MarketPotentialRoute
  '/network': typeof NetworkRoute
  '/sales-enablement': typeof SalesEnablementRouteWithChildren
  '/map/$clusterId': typeof MapClusterIdRoute
  '/plan/past-roadmap': typeof PlanPastRoadmapRoute
  '/map/': typeof MapIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/sales-enablement/': typeof SalesEnablementIndexRoute
  '/plan/$clusterId/review': typeof PlanClusterIdReviewRoute
  '/sales-enablement/$clusterId/$prospectId': typeof SalesEnablementClusterIdProspectIdRoute
  '/plan/$clusterId/': typeof PlanClusterIdIndexRoute
  '/sales-enablement/$clusterId/': typeof SalesEnablementClusterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/market-potential': typeof MarketPotentialRoute
  '/network': typeof NetworkRoute
  '/map/$clusterId': typeof MapClusterIdRoute
  '/plan/past-roadmap': typeof PlanPastRoadmapRoute
  '/map': typeof MapIndexRoute
  '/plan': typeof PlanIndexRoute
  '/sales-enablement': typeof SalesEnablementIndexRoute
  '/plan/$clusterId/review': typeof PlanClusterIdReviewRoute
  '/sales-enablement/$clusterId/$prospectId': typeof SalesEnablementClusterIdProspectIdRoute
  '/plan/$clusterId': typeof PlanClusterIdIndexRoute
  '/sales-enablement/$clusterId': typeof SalesEnablementClusterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/market-potential': typeof MarketPotentialRoute
  '/network': typeof NetworkRoute
  '/sales-enablement': typeof SalesEnablementRouteWithChildren
  '/map/$clusterId': typeof MapClusterIdRoute
  '/plan/past-roadmap': typeof PlanPastRoadmapRoute
  '/map/': typeof MapIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/sales-enablement/': typeof SalesEnablementIndexRoute
  '/plan/$clusterId/review': typeof PlanClusterIdReviewRoute
  '/sales-enablement/$clusterId/$prospectId': typeof SalesEnablementClusterIdProspectIdRoute
  '/plan/$clusterId/': typeof PlanClusterIdIndexRoute
  '/sales-enablement/$clusterId/': typeof SalesEnablementClusterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/market-potential'
    | '/network'
    | '/sales-enablement'
    | '/map/$clusterId'
    | '/plan/past-roadmap'
    | '/map/'
    | '/plan/'
    | '/sales-enablement/'
    | '/plan/$clusterId/review'
    | '/sales-enablement/$clusterId/$prospectId'
    | '/plan/$clusterId/'
    | '/sales-enablement/$clusterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/market-potential'
    | '/network'
    | '/map/$clusterId'
    | '/plan/past-roadmap'
    | '/map'
    | '/plan'
    | '/sales-enablement'
    | '/plan/$clusterId/review'
    | '/sales-enablement/$clusterId/$prospectId'
    | '/plan/$clusterId'
    | '/sales-enablement/$clusterId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/market-potential'
    | '/network'
    | '/sales-enablement'
    | '/map/$clusterId'
    | '/plan/past-roadmap'
    | '/map/'
    | '/plan/'
    | '/sales-enablement/'
    | '/plan/$clusterId/review'
    | '/sales-enablement/$clusterId/$prospectId'
    | '/plan/$clusterId/'
    | '/sales-enablement/$clusterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MarketPotentialRoute: typeof MarketPotentialRoute
  NetworkRoute: typeof NetworkRoute
  SalesEnablementRoute: typeof SalesEnablementRouteWithChildren
  MapClusterIdRoute: typeof MapClusterIdRoute
  PlanPastRoadmapRoute: typeof PlanPastRoadmapRoute
  MapIndexRoute: typeof MapIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  PlanClusterIdReviewRoute: typeof PlanClusterIdReviewRoute
  PlanClusterIdIndexRoute: typeof PlanClusterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-enablement': {
      id: '/sales-enablement'
      path: '/sales-enablement'
      fullPath: '/sales-enablement'
      preLoaderRoute: typeof SalesEnablementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-potential': {
      id: '/market-potential'
      path: '/market-potential'
      fullPath: '/market-potential'
      preLoaderRoute: typeof MarketPotentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-enablement/': {
      id: '/sales-enablement/'
      path: '/'
      fullPath: '/sales-enablement/'
      preLoaderRoute: typeof SalesEnablementIndexRouteImport
      parentRoute: typeof SalesEnablementRoute
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/past-roadmap': {
      id: '/plan/past-roadmap'
      path: '/plan/past-roadmap'
      fullPath: '/plan/past-roadmap'
      preLoaderRoute: typeof PlanPastRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$clusterId': {
      id: '/map/$clusterId'
      path: '/map/$clusterId'
      fullPath: '/map/$clusterId'
      preLoaderRoute: typeof MapClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-enablement/$clusterId/': {
      id: '/sales-enablement/$clusterId/'
      path: '/$clusterId'
      fullPath: '/sales-enablement/$clusterId/'
      preLoaderRoute: typeof SalesEnablementClusterIdIndexRouteImport
      parentRoute: typeof SalesEnablementRoute
    }
    '/plan/$clusterId/': {
      id: '/plan/$clusterId/'
      path: '/plan/$clusterId'
      fullPath: '/plan/$clusterId/'
      preLoaderRoute: typeof PlanClusterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-enablement/$clusterId/$prospectId': {
      id: '/sales-enablement/$clusterId/$prospectId'
      path: '/$clusterId/$prospectId'
      fullPath: '/sales-enablement/$clusterId/$prospectId'
      preLoaderRoute: typeof SalesEnablementClusterIdProspectIdRouteImport
      parentRoute: typeof SalesEnablementRoute
    }
    '/plan/$clusterId/review': {
      id: '/plan/$clusterId/review'
      path: '/plan/$clusterId/review'
      fullPath: '/plan/$clusterId/review'
      preLoaderRoute: typeof PlanClusterIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SalesEnablementRouteChildren {
  SalesEnablementIndexRoute: typeof SalesEnablementIndexRoute
  SalesEnablementClusterIdProspectIdRoute: typeof SalesEnablementClusterIdProspectIdRoute
  SalesEnablementClusterIdIndexRoute: typeof SalesEnablementClusterIdIndexRoute
}

const SalesEnablementRouteChildren: SalesEnablementRouteChildren = {
  SalesEnablementIndexRoute: SalesEnablementIndexRoute,
  SalesEnablementClusterIdProspectIdRoute:
    SalesEnablementClusterIdProspectIdRoute,
  SalesEnablementClusterIdIndexRoute: SalesEnablementClusterIdIndexRoute,
}

const SalesEnablementRouteWithChildren = SalesEnablementRoute._addFileChildren(
  SalesEnablementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MarketPotentialRoute: MarketPotentialRoute,
  NetworkRoute: NetworkRoute,
  SalesEnablementRoute: SalesEnablementRouteWithChildren,
  MapClusterIdRoute: MapClusterIdRoute,
  PlanPastRoadmapRoute: PlanPastRoadmapRoute,
  MapIndexRoute: MapIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  PlanClusterIdReviewRoute: PlanClusterIdReviewRoute,
  PlanClusterIdIndexRoute: PlanClusterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
